[package]
name = "strangetimer-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
serde_derive = "1"
serde_json = { workspace = true }
dirs = { workspace = true }
anyhow = { workspace = true }
