//! `strangetimer completions <shell>` — print a shell completion script.
//!
//! The script comes from the **engine** (clap_complete `unstable-dynamic`),
//! which call back into this binary for live candidates (timer names,
//! buzzer names). It is captured by re-invoking ourselves with
//! `COMPLETE=<shell>` set and no arguments — the engine writes the
//! registration script to stdout in that mode.

use std::process::Command;

use anyhow::Result;

use crate::cli::Shell as ShellArg;

fn shell_name(shell: ShellArg) -> &'static str {
    match shell {
        ShellArg::Bash => "bash",
        ShellArg::Zsh => "zsh",
        ShellArg::Fish => "fish",
        ShellArg::Powershell => "powershell",
    }
}

/// `strangetimer completions <bash|zsh|fish|powershell>`
pub fn print_completions(shell: ShellArg) -> Result<()> {
    print!("{}", script_for(shell));
    Ok(())
}

/// The engine completion script for `shell`, generated by the running
/// binary itself so it always matches the installed CLI.
pub fn script_for(shell: ShellArg) -> String {
    let exe = match std::env::current_exe() {
        Ok(e) => e,
        Err(_) => return String::new(),
    };
    let output = Command::new(exe)
        .env("COMPLETE", shell_name(shell))
        .output()
        .expect("failed to spawn self for completion script");
    String::from_utf8_lossy(&output.stdout).into_owned()
}
