//! `strangetimer completions <shell>` — print a shell completion script.
//!
//! The script comes from the **engine** (clap_complete `unstable-dynamic`),
//! which calls back into the `strangetimer` binary for live candidates
//! (timer names, buzzer names). The registration script is captured by
//! re-invoking ourselves with `COMPLETE=<shell>` set and no arguments.
//!
//! To avoid embedding a stale build path (`target/debug/...`, a CI
//! checkout, ...), the child is spawned with argv[0] = `strangetimer`:
//! the generated script resolves the binary from `$PATH` on every Tab
//! press, so it always talks to the command you actually typed.

use std::process::Command;

use anyhow::{Context, Result};

use crate::cli::Shell as ShellArg;

fn shell_name(shell: ShellArg) -> &'static str {
    match shell {
        ShellArg::Bash => "bash",
        ShellArg::Zsh => "zsh",
        ShellArg::Fish => "fish",
        ShellArg::Powershell => "powershell",
    }
}

/// `strangetimer completions <bash|zsh|fish|powershell>`
pub fn print_completions(shell: ShellArg) -> Result<()> {
    print!("{}", script_for(shell)?);
    Ok(())
}

/// The engine completion script for `shell`, generated by the running
/// binary itself so it always matches the installed CLI. The script calls
/// `strangetimer` (resolved from `$PATH`), never a build path.
pub fn script_for(shell: ShellArg) -> Result<String> {
    let exe = std::env::current_exe().context("cannot resolve own executable")?;
    let mut cmd = Command::new(&exe);
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        // argv[0] controls what the generated script invokes. Use the
        // plain command name so the script follows $PATH.
        cmd.arg0("strangetimer");
    }
    let output = cmd
        .env("COMPLETE", shell_name(shell))
        .output()
        .context("failed to spawn self for completion script")?;
    if !output.status.success() {
        anyhow::bail!(
            "completion script generation failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

/// `strangetimer completions doctor` — diagnose why <Tab> suggestions may
/// be missing, checking the shell integration and the binary in use.
pub fn completion_doctor() -> Result<()> {
    let exe = std::env::current_exe().context("cannot resolve own executable")?;
    println!("strangetimer binary: {}", exe.display());
    println!("version: {}", env!("CARGO_PKG_VERSION"));

    match std::env::var_os("SHELL") {
        Some(shell) => println!("$SHELL: {}", shell.to_string_lossy()),
        None => println!("$SHELL: (unset)"),
    }

    #[cfg(unix)]
    {
        // Where would bash look for an installed completion file?
        let home = dirs::home_dir().unwrap_or_else(|| std::path::PathBuf::from("."));
        let bash_file = home.join(".local/share/bash-completion/completions/strangetimer");
        if bash_file.exists() {
            let content = std::fs::read_to_string(&bash_file).unwrap_or_default();
            let dynamic = content.contains("COMPLETE=") || content.contains("_clap_complete");
            println!(
                "bash completion file: {} ({})",
                bash_file.display(),
                if dynamic {
                    "dynamic engine script"
                } else {
                    "STATIC script - reinstall to get live suggestions"
                }
            );
            // Any stale build paths baked in?
            for needle in ["target/debug", "target/release", "/home/runner"] {
                if content.contains(needle) {
                    println!("  WARNING: stale path {needle:?} embedded - reinstall completions");
                }
            }
        } else {
            println!("bash completion file: (not installed)");
        }
        let fish_file = home.join(".config/fish/completions/strangetimer.fish");
        println!(
            "fish completion file: {} ({})",
            fish_file.display(),
            if fish_file.exists() {
                "installed"
            } else {
                "not installed"
            }
        );
        let zsh_file = home.join(".zfunc/_strangetimer");
        println!(
            "zsh completion file: {} ({})",
            zsh_file.display(),
            if zsh_file.exists() {
                "installed"
            } else {
                "not installed"
            }
        );
    }

    println!();
    println!("To fix: run `strangetimer install-completions` and start a new shell.");
    println!("Check which binary your shell resolves:");
    println!("  type -a strangetimer");
    println!("  complete -p strangetimer   (bash)");
    println!();
    println!("The generated scripts call `strangetimer` via $PATH, so they always");
    println!("talk to the binary you run - no stale build paths are embedded.");
    Ok(())
}
